PSMOVEAPI_VERSION = 26e1446fc9b5996192a1f406d289e64e4e97a195
PSMOVEAPI_SITE = https://github.com/thp/psmoveapi
PSMOVEAPI_SITE_METHOD = git
PSMOVEAPI_INSTALL_STAGING = YES
PSMOVEAPI_GIT_SUBMODULES = YES
#PSMOVEAPI_INSTALL_TARGET = NO
#PSMOVEAPI_CONF_OPTS =
PSMOVEAPI_DEPENDENCIES = host-pkgconf bluez5_utils udev
PSMOVEAPI_CONF_OPTS = -DPSMOVE_BUILD_TRACKER=OFF -DPSMOVE_BUILD_EXAMPLES=OFF -DPSMOVE_BUILD_TESTS=OFF -DPSMOVE_USE_PSEYE=OFF -DPSMOVE_USE_SIXPAIR=OFF

$(eval $(cmake-package))
