SHIP_POSITION_VERSION = v1.4
SHIP_POSITION_SITE = https://github.com/MooseTheBrown/ship-position
SHIP_POSITION_SITE_METHOD = git
SHIP_POSITION_INSTALL_STAGING = YES
#SHIP_POSITION_INSTALL_TARGET = NO
#SHIP_POSITION_CONF_OPTS = -DBUILD_TESTS=ON

$(eval $(cmake-package))
